---

- name: Download files from remote
  hosts: "{{ HOSTS | default([])}}"
  become: false
  gather_facts: false

  roles:
    - role: "roles/zip"
    - role: "roles/copy"
    - role: "roles/sendgcs"
