---

- name: Authenticate with Google Cloud
  become: false
  environment:
    GOOGLE_APPLICATION_CREDENTIALS: "{{ gcs_credentials_file }}"
  vars:
    gcs_credentials_file: "/path/to/gcs_credentials.json"

- name: Upload file to GCS
  gcs:
    bucket: "{{ gcs_bucket_name }}"
    object: "{{ gcs_object_name }}"
    src: "{{ file_to_upload }}"
  vars:
    gcs_bucket_name: "example-bucket"
    gcs_object_name: "example.txt"
    file_to_upload: "/path/to/example.txt"